---
- name: Pacman
  hosts: localhost
  connection: local
  become: yes
  vars_files:
  - ../lists/linux_package_list.yml
  - ../data.txt
  tasks:
  - name: Upgrade pacman
    pacman:
        upgrade: yes
  - name: Install Linux packages with pacman
    pacman:
        name: "{{ pacman_packages }}"
        state: latest

- name: Clear cache
  hosts: localhost
  connection: local
  become: yes
  tasks:
  - name: Clear Linux and AUR caches
    shell: pacman -Scc --noconfirm
