---
- import_playbook: playbooks/generate_datafile.yml
- import_playbook: playbooks/users.yml
- import_playbook: playbooks/linux_packages.yml
- import_playbook: playbooks/ruby_gems.yml
- import_playbook: playbooks/atom_packages.yml
- import_playbook: playbooks/shh_keys.yml
- import_playbook: playbooks/personal_configs.yml
